version: "2.1"

services:
  redis:
    image: "redis:latest"
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - ./volume/redis/data:/redis/data
      - DISABLE_COMMANDS=CONFIG
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --lower_case_table_names=1
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=study
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-proot",  "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

  api:
    build:
      context: study-api
      dockerfile: Dockerfile
    image: colini/study/api:latest
    environment:
      - SPRING_PROFILE=production
      - JVM_MEMORY=-Xmx2g -Xms2g -XX:MetaspaceSize=200m
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthy"]
      interval: 30s
      timeout: 60s
      retries: 15
    links:
      - mysql:mysql
    depends_on:
      mysql:
        condition: service_healthy

  messaging:
    build:
      context: study-messaging
      dockerfile: Dockerfile
    image: colini/study/messaging:latest
    environment:
      - SPRING_PROFILE=production
      - JVM_MEMORY=-Xmx4g -Xms4g -XX:MetaspaceSize=200m
    ports:
      - 8081:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthy"]
      interval: 30s
      timeout: 60s
      retries: 15
    links:
      - redis:redis
      - mysql:mysql
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy